# Classification Recap.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("titanic.csv")
df[:5]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
len(df)

891

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
X_column = ['Pclass', 'Sex', 'SibSp', 'Parch',  'Embarked', 'Survived']
y_column = 'Age'  # 정답값, y, true value, target value, label

# 모델에 사용할 컬럼(column, feature) 결정 
input_data = df[ X_column + [y_column] ].copy()
input_data

Pclass     Sex  SibSp  Parch Embarked  Survived   Age
0         3    male      1      0        S         0  22.0
1         1  female      1      0        C         1  38.0
2         3  female      0      0        S         1  26.0
3         1  female      1      0        S         1  35.0
4         3    male      0      0        S         0  35.0
..      ...     ...    ...    ...      ...       ...   ...
886       2    male      0      0        S         0  27.0
887       1  female      0      0        S         1  19.0
888       3  female      1      2        S         0   NaN
889       1    male      0      0        C         1  26.0
890       3    male      0      0        Q         0  32.0

[891 rows x 7 columns]

In [6]:
input_data[input_data['Age'].isnull()]

Pclass     Sex  SibSp  Parch Embarked  Survived  Age
5         3    male      0      0        Q         0  NaN
17        2    male      0      0        S         1  NaN
19        3  female      0      0        C         1  NaN
26        3    male      0      0        C         0  NaN
28        3  female      0      0        Q         1  NaN
..      ...     ...    ...    ...      ...       ...  ...
859       3    male      0      0        C         0  NaN
863       3  female      8      2        S         0  NaN
868       3    male      0      0        S         0  NaN
878       3    male      0      0        S         0  NaN
888       3  female      1      2        S         0  NaN

[177 rows x 7 columns]

In [7]:
input_data[input_data['Age'].notnull()]

Pclass     Sex  SibSp  Parch Embarked  Survived   Age
0         3    male      1      0        S         0  22.0
1         1  female      1      0        C         1  38.0
2         3  female      0      0        S         1  26.0
3         1  female      1      0        S         1  35.0
4         3    male      0      0        S         0  35.0
..      ...     ...    ...    ...      ...       ...   ...
885       3  female      0      5        Q         0  39.0
886       2    male      0      0        S         0  27.0
887       1  female      0      0        S         1  19.0
889       1    male      0      0        C         1  26.0
890       3    male      0      0        Q         0  32.0

[714 rows x 7 columns]

In [8]:
input_data = input_data[input_data['Age'].notnull()].copy()  # 편의상 Age 가 null값은 제외
input_data

Pclass     Sex  SibSp  Parch Embarked  Survived   Age
0         3    male      1      0        S         0  22.0
1         1  female      1      0        C         1  38.0
2         3  female      0      0        S         1  26.0
3         1  female      1      0        S         1  35.0
4         3    male      0      0        S         0  35.0
..      ...     ...    ...    ...      ...       ...   ...
885       3  female      0      5        Q         0  39.0
886       2    male      0      0        S         0  27.0
887       1  female      0      0        S         1  19.0
889       1    male      0      0        C         1  26.0
890       3    male      0      0        Q         0  32.0

[714 rows x 7 columns]

In [9]:
input_data['Age'].value_counts()

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: Age, Length: 88, dtype: int64

In [10]:
print(input_data['Age'].min())
print(input_data['Age'].max())

0.42
80.0


In [11]:
input_data["Cat_Age"] = "0"
input_data.loc[(input_data["Age"] >= 10 ) & (input_data["Age"] < 20), "Cat_Age"] = "10"
input_data.loc[(input_data["Age"] >= 20 ) & (input_data["Age"] < 30), "Cat_Age"] = "20"
input_data.loc[(input_data["Age"] >= 30 ) & (input_data["Age"] < 40), "Cat_Age"] = "30"
input_data.loc[(input_data["Age"] >= 40 ) & (input_data["Age"] < 50), "Cat_Age"] = "40"
input_data.loc[(input_data["Age"] >= 50 ) , "Cat_Age"] = "50"

In [12]:
input_data["Cat_Age"].value_counts()

20    220
30    167
10    102
40     89
50     74
0      62
Name: Cat_Age, dtype: int64

In [13]:
input_data[["Age", "Cat_Age"]]

Age Cat_Age
0    22.0      20
1    38.0      30
2    26.0      20
3    35.0      30
4    35.0      30
..    ...     ...
885  39.0      30
886  27.0      20
887  19.0      10
889  26.0      20
890  32.0      30

[714 rows x 2 columns]

In [14]:
# 참조
# input_data["Cat_Age_cut"] = pd.cut(input_data["Age"], 7, labels=False)
# input_data["Cat_Age_qcut"] = pd.qcut(input_data["Age"], 7, labels=False)
# input_data[["Age", "Cat_Age", "Cat_Age_cut", "Cat_Age_qcut"]]

In [15]:
input_data.dtypes

Pclass        int64
Sex          object
SibSp         int64
Parch         int64
Embarked     object
Survived      int64
Age         float64
Cat_Age      object
dtype: object

In [16]:
# categorical columns extraction
#cat_cols = ['Sex', 'Embarked']
cat_cols = input_data.columns[input_data.dtypes == object]
cat_cols

Index(['Sex', 'Embarked', 'Cat_Age'], dtype='object')

In [17]:
# label encoding (integer encoding)
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

input_data["Cat_Age_Str"] = input_data["Cat_Age"]

for c in cat_cols:
    input_data[c] = le.fit_transform(list(input_data[c]))  # list() 로 씌우면 결측치 자동 처리

In [18]:
# Embarked
print(le.classes_)
print(input_data['Cat_Age'].unique())

['0' '10' '20' '30' '40' '50']
[2 3 5 0 1 4]


In [19]:
input_data

Pclass  Sex  SibSp  Parch  Embarked  Survived   Age  Cat_Age Cat_Age_Str
0         3    1      1      0         2         0  22.0        2          20
1         1    0      1      0         0         1  38.0        3          30
2         3    0      0      0         2         1  26.0        2          20
3         1    0      1      0         2         1  35.0        3          30
4         3    1      0      0         2         0  35.0        3          30
..      ...  ...    ...    ...       ...       ...   ...      ...         ...
885       3    0      0      5         1         0  39.0        3          30
886       2    1      0      0         2         0  27.0        2          20
887       1    0      0      0         2         1  19.0        1          10
889       1    1      0      0         0         1  26.0        2          20
890       3    1      0      0         1         0  32.0        3          30

[714 rows x 9 columns]

In [20]:
X_column = ['Pclass', 'Sex', 'SibSp', 'Parch',  'Embarked', 'Survived']
y_column = 'Cat_Age'  # 정답값, y, true value, target value, label

In [21]:
# 결측치 체크
input_data.columns[input_data.isna().any()].tolist()

[]

In [22]:
# 결측치 처리
# input_data = input_data.fillna(-1) 

In [23]:
# 데이터 -> train/valid  ,  test
from sklearn.model_selection import train_test_split

tr_val_X, test_X, tr_val_y, test_y = train_test_split(
    input_data[X_column],   # X 입력데이터
    input_data[y_column],   # y 정답데이터
    test_size=0.2,
    shuffle=True,
    random_state=42,
    stratify=input_data[y_column]   # classification 일때는 중요한 옵션
    )

In [24]:
tr_val_data = pd.concat([tr_val_X, tr_val_y], axis=1)
tr_val_data

Pclass  Sex  SibSp  Parch  Embarked  Survived  Cat_Age
670       2    0      1      1         2         1        4
0         3    1      1      0         2         0        2
305       1    1      1      2         2         1        0
632       1    1      0      0         0         1        3
847       3    1      0      0         0         0        3
..      ...  ...    ...    ...       ...       ...      ...
175       3    1      1      1         2         0        1
569       3    1      0      0         2         1        3
575       3    1      0      0         2         0        1
50        3    1      4      1         2         0        0
810       3    1      0      0         2         0        2

[571 rows x 7 columns]

In [25]:
# 데이터 -> train/valid  ,  test
from sklearn.model_selection import train_test_split

train_X, valid_X, train_y, valid_y = train_test_split(
    tr_val_data[X_column],   # X 입력데이터
    tr_val_data[y_column],   # y 정답데이터
    test_size=0.2,
    #train_size=13 # 데이터 개수
    shuffle=True,
    random_state=42,
    stratify=tr_val_data[y_column]   # classification 일때는 중요한 옵션
    )

In [26]:
print(len(train_X))
print(len(valid_X))
print(len(test_X))
len(train_X) + len(valid_X) + len(test_X) # 20

456
115
143


714

In [27]:
456+115+143

714

In [28]:
from catboost import CatBoostClassifier
cb = CatBoostClassifier(verbose=100)
cb.fit(train_X, train_y, eval_set=[(valid_X, valid_y)])

Learning rate set to 0.106294
0:	learn: 1.7470584	test: 1.7625771	best: 1.7625771 (0)	total: 50ms	remaining: 50s
100:	learn: 1.1408548	test: 1.6153047	best: 1.5381487 (36)	total: 160ms	remaining: 1.43s
200:	learn: 1.0620371	test: 1.7277378	best: 1.5381487 (36)	total: 284ms	remaining: 1.13s
300:	learn: 1.0335539	test: 1.8116201	best: 1.5381487 (36)	total: 405ms	remaining: 939ms
400:	learn: 1.0190102	test: 1.8710656	best: 1.5381487 (36)	total: 526ms	remaining: 785ms
500:	learn: 1.0104456	test: 1.9206964	best: 1.5381487 (36)	total: 649ms	remaining: 647ms
600:	learn: 1.0047041	test: 1.9641317	best: 1.5381487 (36)	total: 775ms	remaining: 514ms
700:	learn: 0.9996246	test: 2.0009426	best: 1.5381487 (36)	total: 898ms	remaining: 383ms
800:	learn: 0.9960622	test: 2.0330393	best: 1.5381487 (36)	total: 1.02s	remaining: 254ms
900:	learn: 0.9932351	test: 2.0626267	best: 1.5381487 (36)	total: 1.15s	remaining: 126ms
999:	learn: 0.9906810	test: 2.0880727	best: 1.5381487 (36)	total: 1.27s	remaining: 0us

In [160]:
# classification prediction (예측)
pred_y_prob = cb.predict_proba(test_X)
pred_y_prob

array([[0.01459226, 0.17717708, 0.44652516, 0.18976299, 0.12117017,
        0.05077235],
       [0.13829438, 0.14061625, 0.19162801, 0.24353284, 0.20859847,
        0.07733004],
       [0.13344975, 0.1332579 , 0.17608278, 0.25898309, 0.08959238,
        0.2086341 ],
       [0.01459226, 0.17717708, 0.44652516, 0.18976299, 0.12117017,
        0.05077235],
       [0.01459226, 0.17717708, 0.44652516, 0.18976299, 0.12117017,
        0.05077235],
       [0.01459226, 0.17717708, 0.44652516, 0.18976299, 0.12117017,
        0.05077235],
       [0.01684006, 0.13282835, 0.34984007, 0.22752152, 0.13010826,
        0.14286174],
       [0.03144223, 0.14531386, 0.12820361, 0.36573259, 0.15696741,
        0.1723403 ],
       [0.01459226, 0.17717708, 0.44652516, 0.18976299, 0.12117017,
        0.05077235],
       [0.10063236, 0.13308267, 0.1074753 , 0.31241477, 0.16308136,
        0.18331354],
       [0.03373246, 0.22568584, 0.50985518, 0.13977109, 0.05991105,
        0.03104438],
       [0.04978493, 0

In [161]:
pred_y = np.argmax(pred_y_prob, axis=1)
pred_y

array([2, 3, 3, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 3, 3, 2, 3, 3, 2, 3, 2, 1,
       2, 3, 2, 0, 0, 3, 2, 2, 5, 3, 4, 3, 2, 4, 2, 1, 4, 5, 2, 2, 2, 2,
       1, 2, 2, 2, 3, 5, 2, 4, 0, 4, 2, 2, 2, 2, 2, 0, 2, 2, 4, 2, 0, 4,
       1, 2, 2, 2, 2, 2, 0, 2, 2, 3, 2, 2, 4, 0, 3, 4, 3, 4, 0, 2, 3, 2,
       0, 2, 2, 2, 3, 1, 0, 2, 2, 2, 2, 4, 2, 2, 2, 4, 3, 0, 3, 0, 5, 0,
       2, 3, 2, 2, 2, 2, 3, 2, 3, 0, 3, 3, 3, 5, 2, 2, 2, 4, 3, 3, 2, 1,
       3, 2, 2, 2, 3, 3, 0, 2, 3, 3, 4])

In [162]:
test_y.values

array([2, 1, 1, 4, 1, 4, 1, 3, 2, 4, 3, 1, 3, 2, 1, 1, 4, 3, 3, 3, 3, 3,
       2, 3, 5, 0, 0, 2, 3, 0, 3, 4, 3, 0, 5, 3, 3, 4, 2, 5, 2, 3, 2, 2,
       1, 5, 2, 2, 2, 5, 4, 5, 2, 4, 2, 2, 2, 2, 5, 2, 2, 2, 3, 0, 1, 4,
       3, 2, 3, 2, 2, 2, 0, 2, 2, 2, 4, 3, 2, 0, 2, 5, 0, 5, 0, 1, 2, 1,
       3, 5, 3, 2, 4, 3, 1, 2, 2, 2, 2, 3, 1, 2, 2, 5, 4, 3, 1, 2, 1, 0,
       4, 3, 1, 2, 3, 1, 3, 2, 2, 0, 1, 4, 4, 4, 5, 3, 3, 3, 2, 4, 3, 1,
       3, 3, 3, 2, 5, 2, 0, 1, 5, 4, 5])

In [163]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(test_y, pred_y))

              precision    recall  f1-score   support

           0       0.53      0.67      0.59        12
           1       0.33      0.10      0.15        20
           2       0.43      0.68      0.53        44
           3       0.21      0.21      0.21        34
           4       0.14      0.11      0.12        18
           5       0.40      0.13      0.20        15

    accuracy                           0.36       143
   macro avg       0.34      0.32      0.30       143
weighted avg       0.33      0.36      0.32       143



In [164]:
pd.Series(cb.feature_importances_, index=train_X.columns).sort_values(ascending=False)

Pclass      29.365334
Parch       24.963130
SibSp       14.761325
Survived    12.344744
Embarked     9.322476
Sex          9.242991
dtype: float64

In [29]:
from catboost import CatBoostClassifier
cb = CatBoostClassifier(task_type="GPU",verbose=100)
cb.fit(train_X, train_y, eval_set=[(valid_X, valid_y)])

Learning rate set to 0.097137
0:	learn: 1.7486674	test: 1.7604215	best: 1.7604215 (0)	total: 18.5ms	remaining: 18.5s
100:	learn: 1.1299868	test: 1.6397103	best: 1.5651619 (27)	total: 652ms	remaining: 5.8s
200:	learn: 1.0628951	test: 1.7332297	best: 1.5651619 (27)	total: 1.24s	remaining: 4.94s
300:	learn: 1.0358148	test: 1.8063316	best: 1.5651619 (27)	total: 1.87s	remaining: 4.35s
400:	learn: 1.0210021	test: 1.8657102	best: 1.5651619 (27)	total: 2.5s	remaining: 3.73s
500:	learn: 1.0113290	test: 1.9137852	best: 1.5651619 (27)	total: 3.15s	remaining: 3.14s
600:	learn: 1.0051443	test: 1.9571901	best: 1.5651619 (27)	total: 3.78s	remaining: 2.51s
700:	learn: 1.0000179	test: 1.9936234	best: 1.5651619 (27)	total: 4.5s	remaining: 1.92s
800:	learn: 0.9957696	test: 2.0254116	best: 1.5651619 (27)	total: 5.19s	remaining: 1.29s
900:	learn: 0.9930851	test: 2.0529861	best: 1.5651619 (27)	total: 5.89s	remaining: 647ms
999:	learn: 0.9911023	test: 2.0778453	best: 1.5651619 (27)	total: 6.59s	remaining: 0u

In [30]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(device="cpu", n_estimators=20000)
lgb.fit(train_X, train_y, eval_set=[(valid_X, valid_y)])

[1]	valid_0's multi_logloss: 1.63508
[2]	valid_0's multi_logloss: 1.61488
[3]	valid_0's multi_logloss: 1.59181
[4]	valid_0's multi_logloss: 1.57385
[5]	valid_0's multi_logloss: 1.55773
[6]	valid_0's multi_logloss: 1.54685
[7]	valid_0's multi_logloss: 1.54219
[8]	valid_0's multi_logloss: 1.53847
[9]	valid_0's multi_logloss: 1.53948
[10]	valid_0's multi_logloss: 1.53943
[11]	valid_0's multi_logloss: 1.54078
[12]	valid_0's multi_logloss: 1.54482
[13]	valid_0's multi_logloss: 1.54192
[14]	valid_0's multi_logloss: 1.53875
[15]	valid_0's multi_logloss: 1.53741
[16]	valid_0's multi_logloss: 1.53407
[17]	valid_0's multi_logloss: 1.53552
[18]	valid_0's multi_logloss: 1.54246
[19]	valid_0's multi_logloss: 1.54333
[20]	valid_0's multi_logloss: 1.54291
[21]	valid_0's multi_logloss: 1.54199
[22]	valid_0's multi_logloss: 1.54767
[23]	valid_0's multi_logloss: 1.54817
[24]	valid_0's multi_logloss: 1.55398
[25]	valid_0's multi_logloss: 1.55494
[26]	valid_0's multi_logloss: 1.55622
[27]	valid_0's multi_

LGBMClassifier(device='cpu', n_estimators=20000)

In [32]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='gpu_hist', learning_rate=0.1)
xgb.fit(train_X, train_y, eval_set=[(valid_X, valid_y)])

[10:51:15] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[0]	validation_0-mlogloss:1.75318
[1]	validation_0-mlogloss:1.72084
[2]	validation_0-mlogloss:1.69569
[3]	validation_0-mlogloss:1.67557
[4]	validation_0-mlogloss:1.65921
[5]	validation_0-mlogloss:1.64475
[6]	validation_0-mlogloss:1.63200
[7]	validation_0-mlogloss:1.62236
[8]	validation_0-mlogloss:1.61374
[9]	validation_0-mlogloss:1.60773
[10]	validation_0-mlogloss:1.60287
[11]	validation_0-mlogloss:1.59858
[12]	validation_0-mlogloss:1.59505
[13]	validation_0-mlogloss:1.59245
[14]	validation_0-mlogloss:1.58965
[15]	validation_0-mlogloss:1.58763
[16]	validation_0-mlogloss:1.58535
[17]	validation_0-mlogloss:1.58179
[18]	validation_0-mlogloss:1.57939
[19]	validation_0-mlogloss:1.57724
[20]	validation_0-mlogloss:1.57624
[21]	validation_0-mlog

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=0, importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_delta_step=0,
              max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=80,
              num_parallel_tree=1, objective='multi:softprob', predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
              subsample=1, tree_method='gpu_hist', validate_parameters=1,
              verbosity=None)

In [ ]:
valid_y